# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-12 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webquery', '0002_remove_webquery_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='expression',
            name='gene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webquery.Gene'),
        ),
        migrations.AddField(
            model_name='expression',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webquery.Location'),
        ),
    ]
