# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-13 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webquery', '0004_auto_20161113_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='expression',
            name='express',
            field=models.CharField(default='qqq', max_length=80),
            preserve_default=False,
        ),
    ]
