# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-13 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webquery', '0005_expression_express'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expression',
            name='express',
            field=models.FloatField(default=0.0),
        ),
    ]
