# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-13 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webquery', '0006_auto_20161113_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expression',
            name='express',
            field=models.FloatField(null=True),
        ),
    ]
